CREATE SCHEMA IF NOT EXISTS warehouse;
CREATE SCHEMA IF NOT EXISTS reporting;


CREATE TABLE IF NOT EXISTS warehouse.dim_date (
    date_key INTEGER PRIMARY KEY,
    full_date DATE NOT NULL UNIQUE,
    day_of_month SMALLINT NOT NULL,
    month_number SMALLINT NOT NULL,
    month_name TEXT NOT NULL,
    quarter_number SMALLINT NOT NULL,
    year_number SMALLINT NOT NULL,
    iso_day_of_week SMALLINT NOT NULL,
    day_name TEXT NOT NULL,
    is_weekend BOOLEAN NOT NULL
);


CREATE TABLE IF NOT EXISTS warehouse.dim_product (
    product_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    stock_code TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL,
    product_type TEXT NOT NULL,

    first_seen_at TIMESTAMP,
    last_seen_at TIMESTAMP,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS warehouse.dim_customer (
    customer_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    customer_id TEXT NOT NULL UNIQUE,

    is_unknown BOOLEAN NOT NULL DEFAULT FALSE,

    first_seen_at TIMESTAMP,
    last_seen_at TIMESTAMP,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS warehouse.dim_country (
    country_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    country_name TEXT NOT NULL UNIQUE,

    is_unknown BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO warehouse.dim_product (
    product_key,
    stock_code,
    description,
    product_type,
    is_active
)
VALUES (
    0,
    'UNKNOWN',
    'UNKNOWN PRODUCT',
    'UNKNOWN',
    FALSE
)
ON CONFLICT (product_key) DO NOTHING;


INSERT INTO warehouse.dim_customer (
    customer_key,
    customer_id,
    is_unknown
)
VALUES (
    0,
    'UNKNOWN',
    TRUE
)
ON CONFLICT (customer_key) DO NOTHING;


INSERT INTO warehouse.dim_country (
    country_key,
    country_name,
    is_unknown
)
VALUES (
    0,
    'UNKNOWN',
    TRUE
)
ON CONFLICT (country_key) DO NOTHING;


CREATE TABLE IF NOT EXISTS warehouse.fact_sales (
    sales_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    invoice_date DATE NOT NULL,
    invoice_timestamp TIMESTAMP NOT NULL,

    date_key INTEGER NOT NULL
        REFERENCES warehouse.dim_date(date_key),

    product_key BIGINT NOT NULL
        REFERENCES warehouse.dim_product(
            product_key
        ),

    customer_key BIGINT NOT NULL
        REFERENCES warehouse.dim_customer(
            customer_key
        ),

    country_key BIGINT NOT NULL
        REFERENCES warehouse.dim_country(
            country_key
        ),

    invoice_no TEXT NOT NULL,
    source_row_number BIGINT NOT NULL,

    quantity INTEGER NOT NULL CHECK (
        quantity <> 0
    ),

    unit_price NUMERIC(18, 6) NOT NULL CHECK (
        unit_price >= 0
    ),

    line_amount NUMERIC(24, 6)
        GENERATED ALWAYS AS (
            quantity * unit_price
        ) STORED,

    transaction_type TEXT NOT NULL CHECK (
        transaction_type IN (
            'SALE',
            'ZERO_PRICE',
            'RETURN_OR_ADJUSTMENT',
            'CANCELLATION'
        )
    ),

    is_cancellation BOOLEAN NOT NULL,
    is_zero_price BOOLEAN NOT NULL,
    is_quantity_outlier BOOLEAN NOT NULL,
    is_price_outlier BOOLEAN NOT NULL,

    source_batch_id UUID NOT NULL
        REFERENCES audit.source_files(batch_id),

    source_row_hash CHAR(64) NOT NULL,

    loaded_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (
        invoice_date,
        sales_key
    ),

    UNIQUE (
        invoice_date,
        source_row_hash
    ),

    CHECK (
        NOT is_cancellation
        OR quantity < 0
    )
)
PARTITION BY RANGE (invoice_date);


DO $$
DECLARE
    partition_start DATE;
    partition_end DATE;
    partition_name TEXT;
BEGIN
    FOR partition_start IN
        SELECT generate_series(
            DATE '2010-12-01',
            DATE '2011-12-01',
            INTERVAL '1 month'
        )::DATE
    LOOP
        partition_end :=
            (
                partition_start
                + INTERVAL '1 month'
            )::DATE;

        partition_name :=
            'fact_sales_'
            || to_char(
                partition_start,
                'YYYY_MM'
            );

        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS warehouse.%I '
            'PARTITION OF warehouse.fact_sales '
            'FOR VALUES FROM (%L) TO (%L)',
            partition_name,
            partition_start,
            partition_end
        );
    END LOOP;
END $$;


CREATE TABLE IF NOT EXISTS
warehouse.fact_sales_default
PARTITION OF warehouse.fact_sales DEFAULT;